### ISSUE TITLE
Database learning_analytics_development not created

### ISSUE THREAD

**Issue by lechten** [pantajosef/reveal.js-tracking#4]
Upon `docker-compose up` I get the following error:

```
db_1    | 2020-03-10 08:49:27.631 UTC [65] FATAL:  database "learning_analytics_development" does not exist
web_1   | 2020-03-10 08:49:27 - ActiveRecord::NoDatabaseError - FATAL:  database "learning_analytics_development" does not exist
```

I'm not familiar with ruby (neither sinatra//activerecord), yet. How/when is the database supposed to be created? What might be the reason for this error?

**Comment by pantajosef** [comment]
I'm sorry. I completely forgot about that step in the demo instructions. You have to run `docker-compose run web rake db:create` and `docker-compose run web rake db:migrate` (The web container has to be running) to set up the database. I'll fix this as soon as possible.

**Comment by lechten** [comment]
Thanks for looking into this!  A quick observation: The first command suggests a missing file.

```
rake aborted!
LoadError: cannot load such file -- ./learning_analytics_app
```

**Comment by pantajosef** [comment]
Everything should be working now properly. I added the instructions to the README as well. On my machine everything seemed to work, even as I built the containers over and over again. It seems, I underestimated the caching of docker.

**Comment by pantajosef** [comment]
Quick comment: As it is in the README, the commands are `docker-compose run web bundle exec rake db:create` and `docker-compose run web bundle exec rake db:migrate` respectively.

**Comment by lechten** [comment]
Works for me, thanks! :+1:
